<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="QuickTest Professional" productVer="10.00" os="" host="CARTISIA-PC"><DocLocation><![CDATA[C:\Users\Cartisia\Desktop\Auto\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res3]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Driver_TestSet]]></AName>
<Action rID="T5">
<AName><![CDATA[Driver_TestCase]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:24]]></Time>
<TimeTick>1467338484</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:24]]></Time>
<TimeTick>1467338484</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ 百度一下，你就知道 ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:33]]></Time>
<TimeTick>1467338493</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[[ 百度一下，你就知道 ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Browser ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://60.30.69.61:8290/CESEMDMS/login/loginAction.action<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:33]]></Time>
<TimeTick>1467338493</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" nType="Navigate to http://60.30.69.61:8290/CESEMDMS/login/loginAction.action" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[[ Browser ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ 百度一下，你就知道 ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:34]]></Time>
<TimeTick>1467338494</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[[ 百度一下，你就知道 ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[ELV 环境合规系统]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:36]]></Time>
<TimeTick>1467338496</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[ELV 环境合规系统]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:36]]></Time>
<TimeTick>1467338496</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:36]]></Time>
<TimeTick>1467338496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="24" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["123"]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:36]]></Time>
<TimeTick>1467338496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="27" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[登录.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:36]]></Time>
<TimeTick>1467338496</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="30" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[登录.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="23" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[ELV 环境合规系统]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[来自网页的消息]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:57]]></Time>
<TimeTick>1467338517</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Static ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:57]]></Time>
<TimeTick>1467338517</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="35" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[[ Static ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="34" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[来自网页的消息]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[ELV 环境合规系统_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:57]]></Time>
<TimeTick>1467338517</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[leftFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:57]]></Time>
<TimeTick>1467338517</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["AMDAwAAAACH5BAEAAAAALAAAAAABAA"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (25 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Image<br>image type=Plain Image<br>html tag=IMG<br>alt=<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (25 objects found)&nbsp;</FONT></u><br>
micclass=Image<br>html tag=IMG<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
alt=<SPAN class=passed> (Used</SPAN>, 25 matches)</SPAN><br>image type=Plain Image<SPAN class=passed> (Used</SPAN>, 25 matches)</SPAN><br>html id=tool-1036-toolEl<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>name=Image<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>file name=AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>class=x-tool-expand-bottom<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>width=15<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>height=15<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:57]]></Time>
<TimeTick>1467338517</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="40" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA["AMDAwAAAACH5BAEAAAAALAAAAAABAA"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[AMDAwAAAACH5BAEAAAAALAAAAAABAA.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:57]]></Time>
<TimeTick>1467338517</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="41" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[AMDAwAAAACH5BAEAAAAALAAAAAABAA.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[车型信息.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:01:59]]></Time>
<TimeTick>1467338519</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="44" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[车型信息.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="39" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[leftFrame]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[mainFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:09]]></Time>
<TimeTick>1467338529</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[新增车型.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:09]]></Time>
<TimeTick>1467338529</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="48" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[新增车型.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[关闭.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:13]]></Time>
<TimeTick>1467338533</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="51" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[关闭.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="47" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[mainFrame]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[ELV 环境合规系统_2.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:15]]></Time>
<TimeTick>1467338535</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="54" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[ELV 环境合规系统_2.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[leftFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:15]]></Time>
<TimeTick>1467338535</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[AMDAwAAAACH5BAEAAAAALAAAAAABAA.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:15]]></Time>
<TimeTick>1467338535</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="58" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[AMDAwAAAACH5BAEAAAAALAAAAAABAA.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[车型信息.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:16]]></Time>
<TimeTick>1467338536</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="61" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[车型信息.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="57" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[leftFrame]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[mainFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:24]]></Time>
<TimeTick>1467338544</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[新增车型.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:24]]></Time>
<TimeTick>1467338544</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="65" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[新增车型.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[关闭.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:28]]></Time>
<TimeTick>1467338548</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="68" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[关闭.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="64" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[mainFrame]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[ELV 环境合规系统_2.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:29]]></Time>
<TimeTick>1467338549</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="71" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[ELV 环境合规系统_2.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:36]]></Time>
<TimeTick>1467338556</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:36]]></Time>
<TimeTick>1467338556</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="75" status="Passed" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="74" status="Passed" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ 百度一下，你就知道 ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:46]]></Time>
<TimeTick>1467338566</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="78" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[[ 百度一下，你就知道 ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Browser ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://60.30.69.61:8290/CESEMDMS/login/loginAction.action<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:46]]></Time>
<TimeTick>1467338566</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="80" nType="Navigate to http://60.30.69.61:8290/CESEMDMS/login/loginAction.action" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[[ Browser ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ ELV 环境合规系统 ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:46]]></Time>
<TimeTick>1467338566</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="82" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[[ ELV 环境合规系统 ].Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="38" status="Passed" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[ELV 环境合规系统_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[ELV 环境合规系统]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:47]]></Time>
<TimeTick>1467338567</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["lbx42"]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:47]]></Time>
<TimeTick>1467338567</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="86" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["123456"]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:48]]></Time>
<TimeTick>1467338568</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="89" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[登录.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:48]]></Time>
<TimeTick>1467338568</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="92" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[登录.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="85" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[ELV 环境合规系统]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[来自网页的消息]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:49]]></Time>
<TimeTick>1467338569</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ 用户名或者密码错误！！！ ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:49]]></Time>
<TimeTick>1467338569</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="94" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[[ 用户名或者密码错误！！！ ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ 确定 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:49]]></Time>
<TimeTick>1467338569</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="96" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[[ 确定 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[登陆失败]]></Obj>
<Details ><![CDATA[登录失败！]]></Details>
<Time><![CDATA[2016/7/1 - 10:02:50]]></Time>
<TimeTick>1467338570</TimeTick>
<NodeArgs eType="User" icon="19" nRep="97" status="Passed" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[登陆失败]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="93" status="Passed" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[来自网页的消息]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="22" status="Passed" Source="Driver_TestCase" SourceLine="-1" >
<Disp><![CDATA[ELV 环境合规系统]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/7/1 - 10:01:13" eTime="2016/7/1 - 10:02:52" passed="3" failed="0" warnings="0" ><Param ><ParamName><![CDATA[testCaseFile]]></ParamName><ParamVal><![CDATA[C:\Users\Cartisia\Desktop\Auto\testData\settlement\collection\银行收款.xls]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[testCaseSheetName]]></ParamName><ParamVal><![CDATA[testCase]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Passed" >
<Disp><![CDATA[Driver_TestCase Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2016/7/1 - 10:01:13" eTime="2016/7/1 - 10:02:53" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Driver_TestSet Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Driver Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2016/7/1 - 10:01:10" eTime="2016/7/1 - 10:02:53" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>